manifest:
  remotes:
  - name: infineon
    url-base: https://github.com/infineon

  defaults:
    remote: infineon

  projects:

  # Infineon middleware libraries from public GitHub
  - name: whd-expansion
    remote: infineon
    revision: 54deecc6e51e661cff9e778752d9cf18e90607d5

  - name: wifi-resources
    remote: infineon
    revision: release-v2.0.0

  - name: wifi-connection-manager
    remote: infineon
    revision: release-v3.7.0
